### ISSUE TITLE
Intergration

### ISSUE THREAD

**Issue by DoctorRainer** [louispan/ghcjs-base-stub#5]
I am sorry, but can you add some basic example of how to be able to use Intero's error highlighting (I use vs code with haskero plugin) or help me to figure it out? I just can't figure it out, how for example can I make a hello world reflex project with the error highlighting using intero and this package which claims to make someone to be able to use intero for developing GHCJS project

**Comment by louispan** [comment]
Hi, for an example, please see https://github.com/louispan/javascript-extras/blob/master/javascript-extras.cabal#L37

Basically, ghcjs-base only compile on ghcjs, but you can #if it out and use ghcjs-base stub instead when using vanilla ghc.

Unfortunately, this mechanism only works if you have write-access to the cabal file, so if your dependencies doesn't do this trick, you are kind of stuck.

Please let me know if this is not enough info for you.

**Comment by louispan** [comment]
So in my example above, I could edit the javascript-extras package in vscode using haskero (which uses intero), and compile using `stack build`.

**Comment by DoctorRainer** [comment]
Thanks but for now I am using ghcid in nix-shell

**Comment by louispan** [comment]
It should work the same. As long as all your libraries and packages use the #if trick to use ghcjs-base-stub (and you are only using the subset of ghcjs-base in ghcjs-base-stub - I haven't stubbed everything yet), then you should be able to use ghcid too.
